import Head from 'next/head'
import Image from 'next/image'

import Navbar from '../components/Navbar'
import EventCard from '../components/EventCard'
import StickyHeader from '../components/StickyHeader'
import FilterModal from '../components/FilterModal'
import HomePage from './Home'



export default function Index() {
  return (
    <div >
      <Head>
        <title>Madde 22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Exclude.svg" />
      </Head>

      <HomePage/>

    

    
    </div>
  )
}
