import Head from 'next/head'
import HomePage from './home'



export default function Index() {
  return (
    <div >
      <Head>
        <title>Madde 22</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Exclude.svg" />
      </Head>

      <HomePage/>

    

    
    </div>
  )
}
